### ISSUE TITLE
Difference between OG `d3dcompiler_43.dll` Stand injector?

### ISSUE THREAD

**Issue by hanahaneull** [crwn1337/stand-dll#1]
Is there any specific reason what the problem with the original `d3dcompiler_43.dll` stand injector with this one?
Trying to use it with the OG one seems like its failed to fetch something.

I'm trying to use this project to load other menu, so far it seems injected succesfully. But for the menu I use it seems crashed after few seconds from loading scree. Either something wrong with the injection or it has early injection issue or maybe the menu it just bad.

**Comment by crwn1337** [comment]
The original ones uses (or at least used to when i made this project) a lot of powershell commands, instead of pure winapi functions, which wine does not have (great) support for

**Comment by hanahaneull** [comment]
Current version seems like still using powershell commands, since I tested yesterday and still giving error when try to load with OG `d3dcompiler_43.dll` stand dll.

At first I tested paid menu, sniffed the official injector to extract endpoint to download the dll and make it as a Independent injector. The logs didn't have any useful output (probably has been stripped down).

After some digging, I found there is open source menu called [YimMenu](https://github.com/YimMenu/YimMenu) (Fork of BigBaseV2), tested it with edited `d3dcompiler_43.dll` injector. After looking at the logs, both have the same type of styling. It appear the log ended right when [renderer](https://github.com/YimMenu/YimMenu/blob/master/src/main.cpp#L123-L128) function called, It seems crashing at that state. So it's seems DXVK/ImGUI itself are the issue (Probably DXVK, since there are exist cheat that use ImGUI in linux. Thought it is weird that the paid menu I use are using ImGUI/same rendering method while video showcase didn't show any ImGUI at all and using native menu).

I guess my only options are only use menus that use custom UI.

**Comment by crwn1337** [comment]
I don't think imgui could be the issue here, me and my friends have made multiple internals (on different games) with imgui work on wine, again this is something that you need to debug yourself since I don't have a pc with linux at the moment, but from https://github.com/YimMenu/YimMenu/issues/334 it seems like injecting too early could be the problem, in which you can try using https://github.com/crwn1337/wine_injector where you can inject manually at any time, but it's more annoying to get working because the parameters need to be windows paths and not linux paths.

**Comment by hanahaneull** [comment]
The issue it's actually wine itself smh. Changed from wine-GE (From recommendation in [here](https://github.com/CommandMC/EpicLinux/wiki/GTA-V---Heroic-specific-guide)) to proton-GE and it's works fine injecting it with ASI loader with YimMenu (Not tested injecting with dll injector using other menu, but stand works flawless).

I'll probably fork this injector since YimMenu doesn't have auto update feature YimMenu/YimMenu#2583 by comparing the hash file.

**Comment by crwn1337** [comment]
i added a license (https://github.com/crwn1337/stand-dll/commit/0952abe2b93a32864c5b856dccd6223df311ceda) so youre free to do whatever you want with this project!
