### ISSUE TITLE
Stuttering with stand injected

### ISSUE THREAD

**Issue by ItsMrCube** [crwn1337/stand-dll#2]
Hello, I'm having stuttering issues while Stand is injected as seen below, the stutter happens consistently around once a second and it disappears as soon as I unload stand; the stuttering is very noticeable but the average framerate doesn't really get altered.
The [log](https://github.com/crwn1337/stand-dll/files/13809479/Log.txt) doesn't show anything unusual.
This behavior doesn't happen on Windows 11.

Stand loaded:
![with](https://github.com/crwn1337/stand-dll/assets/25201357/d155dd2d-efcc-4bc2-a24f-a6fe8cc8141b)
Stand unloaded with the `unload` command:
![without](https://github.com/crwn1337/stand-dll/assets/25201357/e7d18c4b-7e6d-4247-8a78-935b7acbb65a)

Edit: This doesn't seem to be an issue while using https://github.com/larsl2005/StandConsoleInjector:
![image](https://github.com/crwn1337/stand-dll/assets/25201357/4e27309a-407e-474e-8bac-9591a957ab87)

(The spike visible all cases is caused by me taking a screenshot)

**Comment by crwn1337** [comment]
This would be kind of hard to track down.

Have you tried seeing the output of wine?
Does using this dll also stutter on windows?
Does deleting these lines help?:
https://github.com/crwn1337/stand-dll/blob/0952abe2b93a32864c5b856dccd6223df311ceda/dll.cpp#L77-L81


I don't really see any difference between the console injector and mine.

**Comment by ItsMrCube** [comment]
Hi, I just tried the dll on windows and the stuttering doesn't happen; I'm not too sure on where to find the wine logs, I had a look at the heroic settings and there wasn't anything different with or without the dll; I also tried compiling the dll myself without that segment to no avail, I'm sorry but I've barely touched C++ development and I have no idea on how to get the necessary headers for dll development.

**Comment by ItsMrCube** [comment]
I'll give proton a try, thanks for the suggestions.
